export const CmsActionTypes = {
  CANCEL_BOOKING_VERIFY_EMAIL_REQUEST: "CANCEL_BOOKING_VERIFY_EMAIL_REQUEST",
  CANCEL_BOOKING_VERIFY_EMAIL_SUCCESS: "CANCEL_BOOKING_VERIFY_EMAIL_SUCCESS",
  CANCEL_BOOKING_VERIFY_EMAIL_ERROR: "CANCEL_BOOKING_VERIFY_EMAIL_ERROR",
};
