export const PreBookingActionTypes = {
  
    ADD_BOOKING_TYPE: "ADD_BOOKING_TYPE",
    ADD_CAR: "ADD_CAR",
    ADD_ACCOUNT_DETAILS: "ADD_ACCOUNT_DETAILS",
    ADD_AMOUNT: "ADD_AMOUNT",
    ADD_EMAIL: "ADD_EMAIL",
    ADD_DIRECTION:"ADD_DIRECTION",
    ADD_MinFair:"ADD_MinFair"
   
}