export const CmsActionTypes = {
  FETCH_BIRTHDAY_PARTY_TRANSFER_PAGE: "FETCH_BIRTHDAY_PARTY_TRANSFER_PAGE",
  FETCH_BIRTHDAY_PARTY_TRANSFER_PAGE_ERROR:
    "FETCH_BIRTHDAY_PARTY_TRANSFER_PAGE_ERROR",
};
