export const CmsActionTypes = {
  UPDATE_ACCOUNT_DETAILS_LOADING: "UPDATE_ACCOUNT_DETAILS_LOADING",
  UPDATE_ACCOUNT_DETAILS_SUCCESS: "UPDATE_ACCOUNT_DETAILS_SUCCESS",
  UPDATE_ACCOUNT_DETAILS_ERROR: "UPDATE_ACCOUNT_DETAILS_ERROR",

  UPDATE_ACCOUNT_PASSWORD_LOADING: "UPDATE_ACCOUNT_PASSWORD_LOADING",
  UPDATE_ACCOUNT_PASSWORD_SUCCESS: "UPDATE_ACCOUNT_PASSWORD_SUCCESS",
  UPDATE_ACCOUNT_PASSWORD_ERROR: "UPDATE_ACCOUNT_PASSWORD_ERROR",
};
