export const CmsActionTypes = {
  CANCEL_BOOKING_PAGE_REQUEST: "CANCEL_BOOKING_PAGE_REQUEST",
  CANCEL_BOOKING_PAGE_SUCCESS: "CANCEL_BOOKING_PAGE_SUCCESS",
  CANCEL_BOOKING_PAGE_ERROR: "CANCEL_BOOKING_PAGE_ERROR",
};
