export const CmsActionTypes = {
  REFUND_REQUEST_LOADING: "REFUND_REQUEST_LOADING",
  REFUND_REQUEST_SUCCESS: "REFUND_REQUEST_SUCCESS",
  REFUND_REQUEST_ERROR: "REFUND_REQUEST_ERROR",

  REFUND_REQUEST_CONFIRM_LOADING: "REFUND_REQUEST_CONFIRM_LOADING",
  REFUND_REQUEST_CONFIRM_SUCCESS: "REFUND_REQUEST_CONFIRM_SUCCESS",
  REFUND_REQUEST_CONFIRM_ERROR: "REFUND_REQUEST_CONFIRM_ERROR",
};
