export const PaymentActionTypes = {
  INITIALIZATION_LOADING: "INITIALIZATION_LOADING",
  INITIALIZATION_SUCCESS: "INITIALIZATION_SUCCESS",
  INITIALIZATION_ERROR: "INITIALIZATION_ERROR",

  EXECUTE_PAYMENT_LOADING: "EXECUTE_PAYMENT_LOADING",
  EXECUTE_PAYMENT_SUCCESS: "EXECUTE_PAYMENT_SUCCESS",
  EXECUTE_PAYMENT_ERROR: "EXECUTE_PAYMENT_ERROR",
};
