export const AuthActionTypes = {
  CONFIRM_PASSWORD_LOADING: "CONFIRM_PASSWORD_LOADING",
  CONFIRM_PASSWORD_SUCCESS: "CONFIRM_PASSWORD_SUCCESS",
  CONFIRM_PASSWORD_ERROR: "CONFIRM_PASSWORD_ERROR",
};
